name: Scrape

on:
  schedule:
    - cron:  '40 2,14 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
            
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            
      - name: Execute python script
        env:
          API_REVIEW: ${{ secrets.API_REVIEW }}
          KEY_TOTAL: ${{ secrets.KEY_TOTAL }}
          KEY_RATINGS: ${{ secrets.KEY_RATINGS }}
          KEY_COUNT: ${{ secrets.KEY_COUNT }}
          KEY_PERC: ${{ secrets.KEY_PERC }}
          KEY_SCORE: ${{ secrets.KEY_SCORE }}
          KEY_UPDATE: ${{ secrets.KEY_UPDATE }}
        run: python scrape.py
        
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "scraped at $TIMESTAMP"
          git push


